[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "npm run build"
  # publish removido para Remix

[build.environment]

[[plugins]]
package = "@netlify/remix-run-plugin"